{"name": "Проверка логина c неправильным логином", "status": "passed", "description": "Пытаемся залогиниться в аккаунт пользователя, получаем ошибку 401 и соотвествующее сообщение", "start": 1721669357318, "stop": 1721669357612, "uuid": "4a2f6032-a3a6-4c6d-9e6b-62827af8b98c", "historyId": "163fbac4a50b86dea237f47a01dd012d", "testCaseId": "163fbac4a50b86dea237f47a01dd012d", "fullName": "tests.test_login_user.TestLoginUser#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-02PLGO0"}, {"name": "thread", "value": "37316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}